### ISSUE TITLE
Image recognition color

### ISSUE THREAD

**Issue by JVKran** [espressif/tflite-micro-esp-examples#18]
Hi @vikramdattu,

As you've stated in the source code, the framebuffer is unsigned while the model expects signed. It's stated that it's good for now, but I spent quite some time on debugging it; for greyscale classification it might be fine, but for coloured images that's not the case.

As it's a trivial change and I suspect quite a lot of users to stumble upon this, I encourage you to implement the suggested change.

Kind regards,

Jochem

**Comment by vikramdattu** [comment]
Hi @JVKran in latest commits, I already took care of this at all the instances:
https://github.com/espressif/tflite-micro-esp-examples/blob/c0ebf5d18e569d253e7883fe91d1099767df25d3/examples/person_detection/main/main_functions.cc#L167

https://github.com/espressif/tflite-micro-esp-examples/blob/c0ebf5d18e569d253e7883fe91d1099767df25d3/examples/person_detection/main/image_provider.cc#L112

https://github.com/espressif/tflite-micro-esp-examples/blob/c0ebf5d18e569d253e7883fe91d1099767df25d3/examples/person_detection/main/image_provider.cc#L96
