### ISSUE TITLE
Error with person detection and ESP32-CAM

### ISSUE THREAD

**Issue by davele2013** [espressif/tflite-micro-esp-examples#28]
Hi,

I have error when boot up custom build for ESP32-CAM for person detection project. 

Please help:

I (30) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (70) camera: Detected camera at address=0x30
I (70) camera: Detected OV2640 camera
I (70) camera: Camera PID=0x26 VER=0x42 MIDL=0x7f MIDH=0xa2
I (160) esp32 ll_cam: node_size: 3072, nodes_per_line: 1, lines_per_node: 4, dma_half_buffer_min:  3072, dma_half_buffer: 12288,lines_per_half_buffer: 16, dma_buffer_size: 24576, image_size: 18432
I (170) cam_hal: buffer_size: 24576, half_buffer_size: 12288, node_buffer_size: 3072, node_cnt: 8, total_cnt: 1
I (180) cam_hal: Allocating 18432 Byte frame buffer in PSRAM
I (180) cam_hal: Allocating 18432 Byte frame buffer in PSRAM
I (190) cam_hal: cam config ok
I (190) ov2640: Set PLL: clk_2x: 0, clk_div: 3, pclk_auto: 1, pclk_div: 8
Camera Initialized

E (1000) spi: spicommon_bus_initialize_io(540): mosi not valid
E (1000) spi_bus: /Users/thuan/Desktop/ESP-IDF/tflite-micro-esp-examples/components/bus/spi_bus.c:78 (spi_bus_create):spi bus create failed
E (1010) screen interface: /Users/thuan/Desktop/ESP-IDF/tflite-micro-esp-examples/components/screen/interface_driver/scr_interface_driver.c:189 (spi_lcd_driver_init):gpio cs invalid
E (1030) screen interface: /Users/thuan/Desktop/ESP-IDF/tflite-micro-esp-examples/components/screen/interface_driver/scr_interface_driver.c:332 (scr_interface_create):screen spi interface create failed
E (1050) screen driver: Screen controller not supported or not enabled in menuconfig

**Comment by vikramdattu** [comment]
@davele2013 thanks for bringing this up. When disabled, CLI only inference, the example is trying to use Camera as well as Screen by default and hence the error.

This definitely needs a fix. Meanwhile, can you please comment out DISPLAY_SUPPORT macro and continue your development: https://github.com/espressif/tflite-micro-esp-examples/blob/72f2c9914561497cbd6ab5d951a83e2462840596/examples/person_detection/main/esp_main.h#L23
