### ISSUE TITLE
cmake Error building examples: cannot find common.cc after syncing from tflite micro

### ISSUE THREAD

**Issue by Tomp0801** [espressif/tflite-micro-esp-examples#29]
This is only the case after running the script sync_from_tflite_micro.sh.
When I build the micro_speech example, this cmake error happens:

```cmake
CMake Error at C:/esp-idf/esp-idf-v4.4.3/tools/cmake/component.cmake:471 (add_library):
  Cannot find source file:

    F:/Repositories/tflite-micro-esp-examples/components/tflite-lib/tensorflow/lite/c/common.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  F:/Repositories/tflite-micro-esp-examples/components/tflite-lib/CMakeLists.txt:70 (idf_component_register)
```

common.cc does not exist at that location (it was there before syncing).
When I change line 52 in CMakeLists.txt of tflite-lib to `"${tflite_dir}/core/c/common.cc"` ( /core/c/ directory, instead of /c/ ), compilation works, but I'm not sure if that is the right file.

Is there maybe an error in the syncing script?

**Comment by vikramdattu** [comment]
@Tomp0801 there have been changes in directory structure in latest `tflite-micro`. CMakeList.txt as a result need these changes.

I have pushed latest sync, this should solve the issue for all.

**Comment by Tomp0801** [comment]
Building works now, thanks
