### ISSUE TITLE
`git clone` command

### ISSUE THREAD

**Issue by FelipeWcosta** [espressif/tflite-micro-esp-examples#50]
When we use the `git clone` command the folders `esp-nn` and `esp32-camera` is empty.

**Comment by aryanxk02** [comment]
Hi @FelipeWcosta,

Execute `git submodule update --init --recursive`

This command is used to initialize and update submodules within a repository.

**Comment by FelipeWcosta** [comment]
Hello @aryanxk02,

Thank you for the help, that's worked!
