### ISSUE TITLE
Edge impulse model problem between ANSI C and NN_OPTIMIZED.

### ISSUE THREAD

**Issue by MichaelDu9226** [espressif/tflite-micro-esp-examples#6]
Hi

I trained an image classification model through edge impulse, then I made some convert and customized based on this project.
In CLI_ONLY_INFERENCE mode, when config ANSI C, the result is correct. But when using NN_OPTIMIZED, the result is incorrect.

My custom work：
1. update new image 0-7, 0-3 is Qianzi(钳子)，4-7 is PCB
2. add some needed OpResolver https://github.com/MichaelDu9226/tflite-micro-esp-examples/blob/f1a42c308896cd588d3897e19c2b9fdab53c5b28/examples/person_detection/main/main_functions.cc#L94

 Is it an optimized operator problem?

This is my fork project, including models and images(0-7) used.
https://github.com/MichaelDu9226/tflite-micro-esp-examples/commit/f1a42c308896cd588d3897e19c2b9fdab53c5b28

**Comment by vikramdattu** [comment]
@MichaelDu9226 thanks for the reporting!
Will try your example and revert back with the solution.

**Comment by MichaelDu9226** [comment]
Hi, @vikramdattu Any updates on this issue? Looking forward to your solution.
Thanks

**Comment by vikramdattu** [comment]
@MichaelDu9226 I am able to reproduce the issue and working on it.
Please use ANSI versions path for now. Will post the update here.

**Comment by MichaelDu9226** [comment]
ok. Thanks for your reply.

**Comment by vikramdattu** [comment]
Hi @advaitjain,
Can you please check the issue and if there is a known remedy for this?

As per my observation, for this particular case, tflite memory allocator ends up assigning same memory pointer for output tensor and scratch buffer.

**Comment by MichaelDu9226** [comment]
@vikramdattu 
I have tested your pull request. The detect_image result is ok now.
Thanks.
