### ISSUE TITLE
Can not include idf head files

### ISSUE THREAD

**Issue by ljdsp** [espressif/tflite-micro-esp-examples#9]
in this project, I can not include idf head files, for example in main.cc:
#include "esp_http_client.h"
#include "esp_console.h"
#include "nvs_flash.h"
#include "protocol_examples_common.h"
the error info as follows:
../main/main.cc:26:10: fatal error: esp_http_client.h: No such file or directory
 #include "esp_http_client.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by vikramdattu** [comment]
@ljdsp 
Which example are you trying to build?
If you are creating your own application, you might have missed some steps.
Easier way is to copy one of the existing examples and make  changes to that.

**Comment by ljdsp** [comment]
I want to use hettp、socket,、console feature in the example  "micro_speech", but the compile error said "../main/main.cc:25:10: fatal error: esp_http_client.h: No such file or directory".  I modify main.cc code as follows, 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

#include "esp_log.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "main_functions.h"
#include "esp_http_client.h"
#include "esp_console.h"
#include "nvs_flash.h"
#include "protocol_examples_common.h"


void tf_main(void) {
  setup();
  while (true) {
    loop();
  }
}

void ld_http_init(void)
{
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());
    ESP_LOGI(TAG, "Connected to AP, begin http example");
}

extern "C" void app_main() {
  ld_http_init();
  xTaskCreate((TaskFunction_t)&tf_main, "tensorflow", 8 * 1024, NULL, 8, NULL);
  vTaskDelete(NULL);
}

**Comment by ljdsp** [comment]
I want to use hettp、socket,、console feature in the example  "micro_speech", but the compile error said "../main/main.cc:25:10: fatal error: esp_http_client.h: No such file or directory".  I modify main.cc code as follows, 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>

#include "esp_log.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "main_functions.h"
#include "esp_http_client.h"
#include "esp_console.h"
#include "nvs_flash.h"
#include "protocol_examples_common.h"


void tf_main(void) {
  setup();
  while (true) {
    loop();
  }
}

void ld_http_init(void)
{
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());
    ESP_LOGI(TAG, "Connected to AP, begin http example");
}

extern "C" void app_main() {
  ld_http_init();
  xTaskCreate((TaskFunction_t)&tf_main, "tensorflow", 8 * 1024, NULL, 8, NULL);
  vTaskDelete(NULL);
}

**Comment by vikramdattu** [comment]
@ljdsp you must also list those components as REQUIRES in CMakeLists.txt file.
e.g., https://github.com/espressif/tflite-micro-esp-examples/blob/60ac067014509cd378e6933bf744c2c6610fd8a4/examples/micro_speech/main/CMakeLists.txt#L11

**Comment by ljdsp** [comment]
ok. thanks
